### ISSUE TITLE
Debugging code that uses date time module

### ISSUE THREAD

**Issue by guziy** [wavebitscientific/datetime-fortran#16]
Hi:

This is more a question than an issue. I have trouble debugging code that uses the date time module. 
**With ddt, compiled with pgi:**
whenever I get in the code where manipulations with date time objects occur (maybe reference to fields...), the gdb process starts consuming enormous amount of memory and it consumes it all...

**With gdb-apple compiled with gfortran:**
eclipse is refusing to show the datetime or timedelta objects (ddt shows the objects but it freezes due to memory issues)

![screen shot 2014-10-01 at 10 00 27](https://cloud.githubusercontent.com/assets/900941/4476162/6a3a383a-4973-11e4-8906-8eec53c91df7.png)

Do you think it is possible to change the type definitions to make them more debugger friendly?

Cheers

**Comment by zbeekman** [comment]
Yes, I find unit tests, integration tests, regression tests, combined with CI tools etc. makes there be very little need for debugging tools.

gdb should work... you may want to install [Homebrew](http://brew.sh) and upgrade gcc/binutils etc.
