### ISSUE TITLE
Automated doc generation with FORD

### ISSUE THREAD

**Issue by milancurcic** [wavebitscientific/datetime-fortran#18]
Current markdown documentation for datetime-fortran is nice but was written by hand. Obviously, this approach worked early on but does not scale with the growth of the project.

The code should be documented in the format that is readable by the amazing [FORD](https://github.com/cmacmackin/ford).

**Comment by szaghi** [comment]
:+1:

**Comment by milancurcic** [comment]
For a small single-module library, this is overkill IMO. + API is described in the README. Closing for now but if somebody wishes to contribute a FORD doc build, please reopen.
