### ISSUE TITLE
add support for mingw

### ISSUE THREAD

**Issue by sunt05** [wavebitscientific/datetime-fortran#54]
As [`mingw` lacks `strptime`](https://stackoverflow.com/questions/321849/strptime-equivalent-on-windows?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa), it would be good that support could be provided to use this very handy module under `mingw`.

**Comment by milancurcic** [comment]
Following the answer in the link, you'd need to build the related C routines and `tm_struct` along with your app before linking with datetime. 

This is outside of scope for datetime-fortran, but I'm curious about your solution and it may be useful for other mingw users.
