### ISSUE TITLE
Can't build tests on win-ifort. Fails on linker with strptime

### ISSUE THREAD

**Issue by RBCanelas** [wavebitscientific/datetime-fortran#55]
Hello,

I have been using your library with no problems in unix with gfortran, but time has come to compile things in Windows using ifort.

Compiling the library runs, although some warnings do show up. Compiling the tests fails with 

Severity	Code	Description	Project	File	Line	Suppression State
Error		error LNK2019: unresolved external symbol strptime referenced in function MOD_DATETIME_mp_STRPTIME		datetime.lib(mod_datetime.obj)

I'm a bit stuck, any ideas?

**Comment by milancurcic** [comment]
Looks like it could be related to https://github.com/wavebitscientific/datetime-fortran/issues/54.

Any chance of trying WSL (Windows Sybsystem for Linux)? I built and used datetime-fortran in WSL last year, without issues. This assumes you'd have to install the Linux version of ifort in there.

Unfortunately, I don't have access to a Windows machine (nor ifort for Windows) so my input will be limited.

**Comment by RBCanelas** [comment]
Hey, thanks for the quick reply. Unfortunately wsl isn't an option as the project is used primarily by win users. I'm called insane for developing in linux.
Thank you, but i might need to move on. Cheers!

**Comment by dcdenu4** [comment]
I had the exact error related to strptime on Windows using MinGW/MSYS, but I tried out the WSL, specifically Ubuntu and was able to build following the "Building with cmake" instructions without problems. I had to use sudo for the cmake and make commands but that was it. 

I then was able to copy the include and lib folder to my project and compile my executable via makefile using gfortran from MinGW.

**Comment by xxtt** [comment]
> I then was able to copy the include and lib folder to my project and compile my executable via makefile using gfortran from MinGW.
Could you explain a little more about "combining include and lib with project"? I tried to use the "*.mod" in WSL, put them into MinGW, but an error occur: Fatal Error: Cannot read module file 'datetime_module.mod' opened at (1), because it was created by a different version of GNU Fortran compilation terminated.
