### ISSUE TITLE
Dealing with huge timedelta values

### ISSUE THREAD

**Issue by alexavr** [wavebitscientific/datetime-fortran#58]
Hello, 
Once again thank you for this saving life lib!

I have to deal with datasets where time is written as, say, "seconds since 1900-01-01 ...".  In order to convert any modern date into this format, I need to subtract 1900-01-01 from it and than convert into seconds using *total_seconds*. Obviously. But the *total_seconds* function becomes crazy if the number of days exceeds 68 years. It happens because privates in *timedelta* (days,hours,etc) are integer(4) by default and hence in *total_seconds* `self % days*86400`=68x365x86400 seconds exceeds HUGE(integer(4)): 
```fortran
  total_seconds = self % days*86400 + self % hours*3600&
                + self % minutes*60 + self % seconds   &
                + self % milliseconds*1e-3_real64
```

**Fast check**:
```fortran
program test
use datetime_module
implicit none

type(datetime)  :: a,b
type(timedelta) :: c
integer :: ii

    ! print*,"Setting a very long period (approx. 63 to 74 year)"
    do ii = 23000, 27000, 100
         c = timedelta(days=ii)
         print*,ii,c%total_seconds()
     end do

end program test
```

**Fast and rough cure**: recompile the datetime-fortran lib using integer(8) by default. For Intel Compiler it would look like this:
```bash
FC=ifort FCFLAGS='-g -i8' ./configure --prefix=/path/to/folder 
make 
make install
```
It did the trick for me.

**Comment by milancurcic** [comment]
Hi alexavr, great catch! I can reproduce this. 

No compiler promotion for all integers is necessary. The addition of integers goes left-to-right here (even though not defined by the standard and compiler-dependent), so integer overflow occurs before we get to multiplying with milliseconds. 

The correct and easy solution IMO is to multiply with a 64-bit float at the start:

```fortran
  total_seconds = 1._real64 * self % days*86400 + self % hours*3600&
                + self % minutes*60 + self % seconds   &
                + self % milliseconds*1e-3_real64
```

I tested this with your program. With this solution, we can work with 32-bit integers and floats for most stuff, and use 64-bit where needed.

**Comment by alexavr** [comment]
Very good idea!
Works for me. 
Appreciated!

**Comment by milancurcic** [comment]
Do you mind submitting this fix as a PR? 

1. Fork this repo
2. `git clone https://github.com/alexavr/datetime-fortran`
3. Make your changes
4. git add, commit, and push to alexavr/datetime-fortran
5. Open Pull Request from your repo page.

**Comment by alexavr** [comment]
Are you kidding? I'll be honored! 
Give me some little time to learn how to do that LOL

**Comment by milancurcic** [comment]
This is fixed in latest relase: https://github.com/wavebitscientific/datetime-fortran/releases/tag/v1.6.1. Thanks @alexavr.
