### ISSUE TITLE
Bug in function now()

### ISSUE THREAD

**Issue by weixing1531** [wavebitscientific/datetime-fortran#62]
There is a bug in the file "mod_datetime.f90".
type(datetime) function now()
...
now % tz = hour+minute*m2h
Codes should be change to
now % tz = hour+sign(minute,hour)*m2h
or 
now % tz = values(4)*m2h

**Comment by milancurcic** [comment]
Thanks a lot -- I believe you are correct. Can you give an example case in which the current code produces an erroneous value? I'm trying to understand it better.

**Comment by weixing1531** [comment]
For example, if you are in New York or someplace, zone=="-0530", then hour==-5 and minute==30
now % tz = hour+minute*m2h
so tz==-4.50, it is wrong!
the right answer is -5.50!

**Comment by weixing1531** [comment]
For example, if you are in New York or someplace, zone=="-0530", then hour==-5 and minute==30
now % tz = hour+minute*m2h
so tz==-4.50, it is wrong!
the right answer is -5.50!

 
------------------
姓名：魏兴
工作单位：新疆水利水电勘测设计研究院规划所
手机：13565969591
邮箱：282844965@qq.com


 




------------------ 原始邮件 ------------------
发件人: "Milan Curcic"<notifications@github.com>; 
发送时间: 2019年9月24日(星期二) 凌晨4:56
收件人: "wavebitscientific/datetime-fortran"<datetime-fortran@noreply.github.com>; 
抄送: "尼古拉斯·魏"<282844965@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wavebitscientific/datetime-fortran] Bug in function now() (#62)




Thanks a lot -- I believe you are correct. Can you give an example case in which the current code produces an erroneous value? I'm trying to understand it better.

**Comment by weixing1531** [comment]
For example, if you are in New York or someplace, zone=="-0530", then hour==-5 and minute==30
now % tz = hour+minute*m2h
so tz==-4.50, it is wrong!
the right answer is -5.50!
