### ISSUE TITLE
Function that ingests ISO format and returns datetime?

### ISSUE THREAD

**Issue by mathomp4** [wavebitscientific/datetime-fortran#66]
Just a question to make sure. I’d like to convert a project I work on from its own date time format to using ISO date format. So instead of “20170607 124500” in a startup file, I’d love to say “2017-06-07T12:45:00”. I know datetime-fortran can convert a datetime object into an ISO format string, but can it do the opposite? (And I guess similar for durations?)

Or because python-datetime doesn’t (it’s part of dateutil parser) this project might not do so (I.e., time to write fortran-dateutil?)

**Comment by milancurcic** [comment]
Hi Matt,

Sure you can. You're looking for strptime:

```fortran
program strptime_example
  use datetime_module, only: datetime, strptime
  implicit none
  type(datetime) :: a
  a = strptime('20170607 124500', '%Y%m%d %H%M%S')
  print *, a % strftime('%Y-%m-%dT%H:%M:%S')
end program strptime_example
```

Python datetime has the same thing, but there it's a type-bound method, i.e. `datetime.datetime.strptime`.

To be honest, `datetime % strftime()` and `strptime()` is what I use in datetime-fortran the most.
