### ISSUE TITLE
Processing of `secondsSinceEpoch` and its reverse processing routine.

### ISSUE THREAD

**Issue by sakamoti** [wavebitscientific/datetime-fortran#79]
When I try to get Epoch time using `secondsSinceEpoch` , results of these values are different from C language's `mktime` function's results. `datetime-fortran` calculate epoc time with own routine (`secondsSinceEpoch`), and don't use time zone information.
So, I fixes to use time zone information to calculate epoc time, and confirmed to be same as C language's `mktime` function results.
(I believe that `secondsSinceEpoch` is correct with UTC time zone.)

https://github.com/sakamoti/datetime-fortran

In addition, reverse processing routine (`secondsSinceEpoch` to `type(datetime)`) is added to this library with using C language's `localtime_r` and `gmtime_r`.

As a result, it would be possible to interconvert between `secondsSinceEpoch` expressed in int64 and `type(datetime)` , and it would be easier to work with C and Python.
Furthermore, I believe that the conversion to integer type will enable users to speed up the computation time with their own ingenuity.

My fork repository on the above github souce achieves these things.

I would be happy to be merged these features, but I created this issue here first in case there are better ways or other opinions.

**Comment by milancurcic** [comment]
Done by #80
